### ISSUE TITLE
File and directory permission left as root user.

### ISSUE THREAD

**Issue by BigDataDaddy** [aws-samples/emr-presto-query-event-listener#2]
The script emr-presto-query-event-listener/eventlistenerbootstraptemplate.sh used the sudo command to create directories and copy files leaving them with root:root owner and group permissions.  For an EMR Presto installation these files and directories should really have presto:presto  owner and group permissions.  A simple "sudo chown presto:presto ...." after each operation should do the trick.

**Comment by kapadiazafar** [comment]
Greetings,

Apologize for the delayed response. We have been looking into this issue and should have an update for you soon.

Thanks,

Regards,

Zafar.

**Comment by kapadiazafar** [comment]
Greetings,

As the presto user does not exist when the bootstrap action runs. You can run a script in all the instances after the cluster is up. Another option is to create a bootstrap action that takes into consideration the time the user presto is created and changes the folder ownership of the plugin artifacts from root to presto.

Please let us know if you have any questions.

Regards,

Zafar.
