### ISSUE TITLE
Event listener log file incompatible with EMR logpusher.

### ISSUE THREAD

**Issue by BigDataDaddy** [aws-samples/emr-presto-query-event-listener#3]
This Presto event log listener is writing a query log file using the java.util.logging.FileHandler directly in a way which is not compatible with the EMR logpusher that rotates, compresses, and pushes logs to S3.  

The effect of this is that log files written by this event listener are not durable enough (i.e. in S3) to survive EMR cluster termination like the Presto http-server.log and server.log files are.

For a logger to be compatible with EMR logpusher it shouldn't lock the log file and let logpusher handle the file compression and deletion while the logger can handle log file size rolling.

Also any Presto plugin would be better off using Presto's logger inherited from Airlift that is already compatible with the EMR logpusher as long as the Presto configured log file retention is set higher than the  EMR configuration for the EMR app, which for Presto is in /etc/logpusher/presto.config. 

IMO, a better design would be to follow the Presto configuration property pattern for Presto "http-server.log.*" properties in the event listeners configuration file and then set those properties in Airlift call like Presto does.  This would make the event listeners log equivalent in functionality to the Presto http-server.log and server.log configurations.

**Comment by kapadiazafar** [comment]
Greetings,

Thank you for opening the issue. We do see the query log files are rotated, compressed and pushed to S3. Please see the attached screenshot. Let us know if you have further questions or concerns. We will be glad to address them.

![emrlogs](https://user-images.githubusercontent.com/34280467/41999954-3752132c-7a2d-11e8-8bae-df7caa46fd56.PNG)

**Comment by BigDataDaddy** [comment]
Hi,

Thanks for the follow-up on this issue.  

All the following is from the EMR master node of an EMR 5.13.0 cluster with Presto and Hive.

I've have configured EMR to retain 30 days of Presto logs on the cluster using /etc/logpusher/presto.config as follows:

_[ec2-user@ip-xx-xxx-xxx-xxx ~]$ cat /etc/logpusher/presto.config
{
  "/var/log/presto" : {
    "includes" : [ "(.*)" ],
    "s3Path" : "node/$instance-id/applications/presto/$0",
    "retentionPeriod" : "30d",
    "logType" : [ "USER_LOG", "SYSTEM_LOG" ]
  }
}
[ec2-user@ip-xx-xxx-xxx-xxx ~]$_

I've also set the 2 Presto config properties:

_http-server.log.max-history=30
log.max-history=30_

but I set them on different days, each 3 days after the oldest http-server.log and server.log file in /var/log/presto as shown below:

_presto ~ > ls -al /var/log/presto
total 801060
drwxr-xr-x  2 presto presto      4096 Jun 28 00:00 .
drwxr-xr-x 26 hadoop hadoop      4096 Jun 24 03:18 ..
-rw-r--r--  1 presto presto 232293920 Jun 28 15:49 http-request.log
-rw-r--r--  1 presto presto   7623837 Jun  6 00:00 http-request.log-2018-06-05.0.log.gz
-rw-r--r--  1 presto presto   7770427 Jun  7 00:00 http-request.log-2018-06-06.0.log.gz
-rw-r--r--  1 presto presto   8593270 Jun  8 00:00 http-request.log-2018-06-07.0.log.gz
-rw-r--r--  1 presto presto   8419803 Jun  9 00:00 http-request.log-2018-06-08.0.log.gz
-rw-r--r--  1 presto presto   7661005 Jun 10 00:00 http-request.log-2018-06-09.0.log.gz
-rw-r--r--  1 presto presto   7626305 Jun 11 00:00 http-request.log-2018-06-10.0.log.gz
-rw-r--r--  1 presto presto   7806499 Jun 12 00:00 http-request.log-2018-06-11.0.log.gz
-rw-r--r--  1 presto presto   8082073 Jun 13 00:00 http-request.log-2018-06-12.0.log.gz
-rw-r--r--  1 presto presto   7854682 Jun 14 00:00 http-request.log-2018-06-13.0.log.gz
-rw-r--r--  1 presto presto   8754064 Jun 15 00:00 http-request.log-2018-06-14.0.log.gz
-rw-r--r--  1 presto presto   9496427 Jun 16 00:00 http-request.log-2018-06-15.0.log.gz
-rw-r--r--  1 presto presto   8843847 Jun 17 00:00 http-request.log-2018-06-16.0.log.gz
-rw-r--r--  1 presto presto   8711203 Jun 18 00:00 http-request.log-2018-06-17.0.log.gz
-rw-r--r--  1 presto presto   8808010 Jun 19 00:00 http-request.log-2018-06-18.0.log.gz
-rw-r--r--  1 presto presto   8324558 Jun 20 00:00 http-request.log-2018-06-19.0.log.gz
-rw-r--r--  1 presto presto   7433449 Jun 21 00:00 http-request.log-2018-06-20.0.log.gz
-rw-r--r--  1 presto presto  10773005 Jun 22 00:00 http-request.log-2018-06-21.0.log.gz
-rw-r--r--  1 presto presto   9125827 Jun 23 00:00 http-request.log-2018-06-22.0.log.gz
-rw-r--r--  1 presto presto  11085919 Jun 24 00:00 http-request.log-2018-06-23.0.log.gz
-rw-r--r--  1 presto presto  10894519 Jun 25 00:00 http-request.log-2018-06-24.0.log.gz
-rw-r--r--  1 presto presto  12505771 Jun 26 00:00 http-request.log-2018-06-25.0.log.gz
-rw-r--r--  1 presto presto  13277832 Jun 26 20:11 http-request.log-2018-06-26.0.log.gz
-rw-r--r--  1 presto presto   2991802 Jun 27 00:00 http-request.log-2018-06-26.1.log.gz
-rw-r--r--  1 presto presto  13761866 Jun 27 17:31 http-request.log-2018-06-27.0.log.gz
-rw-r--r--  1 presto presto   4833419 Jun 28 00:00 http-request.log-2018-06-27.1.log.gz
-rw-r--r--  1 presto presto  39274689 Jun 27 21:10 launcher.log
-rw-r--r--  1 presto presto     99513 Jun 27 21:10 queries-2018-06-26T20:35:48.0.log
-rw-r--r--  1 presto presto         0 Jun 26 20:35 queries-2018-06-26T20:35:48.0.log.lck
-rw-r--r--  1 presto presto  31641551 Jun 27 21:10 server.log
-rw-r--r--  1 presto presto    345554 May 31 00:46 server.log-2018-05-30.0.log
-rw-r--r--  1 presto presto   2216244 Jun 14 20:05 server.log-2018-06-14.0.log.gz
-rw-r--r--  1 presto presto   1875824 Jun 14 21:35 server.log-2018-06-14.1.log.gz
-rw-r--r--  1 presto presto   1970630 Jun 14 22:24 server.log-2018-06-14.2.log.gz
-rw-r--r--  1 presto presto   2134697 Jun 14 23:17 server.log-2018-06-14.3.log.gz
-rw-r--r--  1 presto presto    620368 Jun 15 15:01 server.log-2018-06-14.4.log.gz
-rw-r--r--  1 presto presto   1966135 Jun 15 17:34 server.log-2018-06-15.0.log.gz
-rw-r--r--  1 presto presto   1970891 Jun 15 18:41 server.log-2018-06-15.1.log.gz
-rw-r--r--  1 presto presto   2012301 Jun 15 20:21 server.log-2018-06-15.2.log.gz
-rw-r--r--  1 presto presto    478738 Jun 16 07:23 server.log-2018-06-15.3.log.gz
-rw-r--r--  1 presto presto     11479 Jun 18 15:29 server.log-2018-06-16.0.log.gz
-rw-r--r--  1 presto presto   1981867 Jun 18 16:14 server.log-2018-06-18.0.log.gz
-rw-r--r--  1 presto presto   2010341 Jun 18 17:25 server.log-2018-06-18.1.log.gz
-rw-r--r--  1 presto presto   1947469 Jun 18 18:15 server.log-2018-06-18.2.log.gz
-rw-r--r--  1 presto presto   1971872 Jun 18 21:35 server.log-2018-06-18.3.log.gz
-rw-r--r--  1 presto presto    676905 Jun 19 15:37 server.log-2018-06-18.4.log.gz
-rw-r--r--  1 presto presto   1884194 Jun 19 17:44 server.log-2018-06-19.0.log.gz
-rw-r--r--  1 presto presto   1346219 Jun 20 15:58 server.log-2018-06-19.1.log.gz
-rw-r--r--  1 presto presto   2015102 Jun 20 22:24 server.log-2018-06-20.0.log.gz
-rw-r--r--  1 presto presto   1629373 Jun 21 15:18 server.log-2018-06-20.1.log.gz
-rw-r--r--  1 presto presto   2093431 Jun 21 17:04 server.log-2018-06-21.0.log.gz
-rw-r--r--  1 presto presto    207322 Jun 22 19:54 server.log-2018-06-21.1.log.gz
-rw-r--r--  1 presto presto   1947255 Jun 22 21:14 server.log-2018-06-22.0.log.gz
-rw-r--r--  1 presto presto    208417 Jun 25 13:53 server.log-2018-06-22.1.log.gz
-rw-r--r--  1 presto presto   1865239 Jun 25 15:24 server.log-2018-06-25.0.log.gz
-rw-r--r--  1 presto presto   1991790 Jun 25 17:40 server.log-2018-06-25.1.log.gz
-rw-r--r--  1 presto presto   2024536 Jun 25 18:51 server.log-2018-06-25.2.log.gz
-rw-r--r--  1 presto presto    844483 Jun 26 13:34 server.log-2018-06-25.3.log.gz
-rw-r--r--  1 presto presto   1932265 Jun 26 17:54 server.log-2018-06-26.0.log.gz
-rw-r--r--  1 presto presto   1873765 Jun 26 18:37 server.log-2018-06-26.1.log.gz
-rw-r--r--  1 presto presto   1955859 Jun 26 21:30 server.log-2018-06-26.2.log.gz
-rw-r--r--  1 presto presto   1710196 Jun 27 14:36 server.log-2018-06-26.3.log.gz
-rw-r--r--  1 presto presto   1962640 Jun 27 20:47 server.log-2018-06-27.0.log.gz
presto ~ >_

The event listener has been part of the running Presto coordinator on the EMR master node for the last 3 days.  As you can see from the above log file list the Presto http-server.log and server.log files are getting rolled and retained by Presto daily and compressed and retained by the logpusher (every 5 min).  However, the  event listeners first log file, queries-2018-06-26T20:35:48.0.log, hasn't been rolled, because  Presto's logger isn't managing it nor has it been compressed by logpusher for the last 3 days.

I see a lock file (queries-2018-06-26T20:35:48.0.log.lck) on the event listener's query log.  So I'm wondering if that is blocking what that logpusher is supposed to be doing.  Also, there aren't lock files on the other Presto logs.  I believe that's because Presto is using the Airlift logger whereas the event listener is using the Java logger (java.util.logging.FileHandler) directly.

Thanks!

**Comment by kapadiazafar** [comment]
Greetings,

Can you please send me your code which initializes the file handler.

Thanks,

Zafar.

**Comment by kapadiazafar** [comment]
Greetings,

Can you please run the command below and send us the output.

tail /emr/logpusher/log/logpusher.log

Thanks!

**Comment by kapadiazafar** [comment]
Did not get a reply from me previous communication.

**Comment by kapadiazafar** [comment]
Did not get a reply from me previous communication.
